### ISSUE TITLE
Create endorsed button on frontend

### ISSUE THREAD

**Issue by evelynnchen-cmu** [CMU-313/nodebb-f24-boba#23]
Estimated effort: 20 hours
Acceptance criteria: Get through [setting up how to develop changes to Harmony theme](https://docs.google.com/document/d/1HCb6FL6noy3CYv2HG1Ea3ZHHN1uLghwcArk_c2TSrzg/edit) and able to see a button on the frontend

**Comment by minghanm** [comment]
This feature is done in the repository nodebb-frontend-f24-boba.
![Image](https://github.com/user-attachments/assets/b6fdd3b5-bfba-4984-aacc-22b01a78f78d)
Still need to connect with the backend logic.
