### ISSUE TITLE
Plan out functionality and UI (if needed) for US1 feature

### ISSUE THREAD

**Issue by AliceeLe** [CMU-313/nodebb-f24-boba#8]
Estimated effort: 1-1.5 hours
Dependencies: None
Acceptance criteria: Brainstorm documentation and rough wireframe for that feature

**Comment by minghanm** [comment]
For the endorsement feature, we planned to implement an endorsement button that is visible only to admins. This button allows admins to mark a post as "endorsed" by clicking it, and they can re-click the button to remove the endorsement if needed. For the BE functionality, we planed to add necessary API routes and endpoints, and the feature emulates existing patterns like votes.
